brands:
  RegistrationPrice: 250000
  ApplicationPrice: 10000
items:
  shampoo:
    lore:
    - Soak your horse, then
    - apply this shampoo. Allow
    - it to work for 30-60
    - seconds then scrape off
    - thoroughly with Sweat
    - Scraper.
  sweat_scraper:
    lore:
    - First soak, then shampoo
    - your horse. Remove water
    - and moisture with this
    - tool by scraping it with
    - the grain.
  clippers:
    lore:
    - Trim the fur of your horse
    - these clippers. Batteries
    - last up to 16 hours.
  hard_brush:
    lore:
    - This brush has hard
    - bristles to remove dirt
    - and hair. Only use this on
    - the sides of the body,
    - brushing from top to
    - bottom with the
    - hair. Never apply the hard
    - brush on the face or legs
    - or under the belly as they
    - are very sensitive.
  hoof_pick:
    lore:
    - Remove dirt from between
    - the hooves
  curry_comb:
    lore:
    - This soft brush removes
    - dirt, scurf, or dander,
    - from the horse's skin,
    - distributes the oils
    - throughout its fur and
    - stimulate the skin. It
    - promotes an overall shiny,
    - healthy coat. Apply it
    - with slow, circular
    - movements from head to
    - tail.
  shedding_blade:
    lore:
    - Use this blade to remove
    - shedding hair from the
    - horse's coat.
  mane_and_tail_comb:
    lore:
    - Comb the mane and tail
    - with this soft brush.
  face_brush:
    lore:
    - Used to brush your horse's
    - face.
  hoof_oil:
    lore:
    - Polish the surface of the
    - hooves with this fine
    - product. Contains coconut
    - oil.
  show_sheen:
    lore:
    - Spray the show sheen on
    - the coat to make it appear
    - smooth and shiny.
  foal_mix:
    lore:
    - Feed this to foals so
    - they can grow up.