name: Horse
version: 1.0
author: StarTux
main: net.equestriworlds.horse.HorsePlugin
website: https://equestriworlds.net
depend: [Vault]
softdepend: []
commands:
  horse:
    aliases: [h]
    description: Horse management
    permission: horse.horse
    usage: |-
      /h - Open horse menu
      /h list - List your horses
      /h claim - Claim your horse
      /h rename <name> - Rename horse
      /h here - Bring the horse
      /h info - Information about your horse
      /h registerbrand - Register brand
      /h brandlist - List brands
      /h help - Usage
  vet:
    aliases: [vh]
    descripton: Horse vet command
    permission: horse.vet
    usage: |-
      /vh birth - Initiate birth
      /vh abort - Abort baby horse
  horseadmin:
    aliases: [ha]
    description: Admin interface
    permission: horse.admin
    usage: |-
      /ha - Overview
      /ha new - Edit new horse
      /ha edit - Edit existing horse
      /ha deletebrand <owner> - Delete horse brand
      /ha spawntool <tool|all> [player] - Spawn horse tool.
      /ha spawnfeed <feed|all> [amount] [player] - Spawn horse feed.
permissions:
  horse.horse:
    description: Use /h
    default: op
  horse.admin:
    description: Use /ha
    default: op
  horse.vet:
    description: Licensed to be a veterenarian.
    default: op
  horse.farrier:
    description: Licensed to be a hoof expert.
    default: op
  horse.floater:
    description: Licensed to be a horse dentist.
    default: op
