name: Horse
version: 1.0
author: StarTux
main: net.equestriworlds.horse.HorsePlugin
website: https://equestriworlds.net
depend: []
softdepend: []
commands:
  horse:
    aliases: [ h ]
    description: Horse management
    usage: |-
      /h claim - Claim your horse
      /h list - List your horses
      /h here - Bring the horse
      /h info - Information about your horse
      /h help - Usage
    permission: horse.horse
permissions:
  horse.horse:
    description: Use /h
    default: op
