name: Horse
version: 1.0
author: StarTux
main: com.equestriworlds.horse.Horse
website: https://equestriworlds.net
depend: []
softdepend: []
commands:
  horse:
    aliases: [ h ]
    description: Horse management
    usage: |-
      /h claim - Claim your horse
      /h here - Bring the horse
      /h info - Information about your horse
    permission: horse.horse
permissions:
  horse.horse:
    description: Use /h
    default: op
