name: Horse
version: 1.0
author: StarTux
main: net.equestriworlds.horse.HorsePlugin
website: https://equestriworlds.net
depend: []
softdepend: []
commands:
  horse:
    aliases: [h]
    description: Horse management
    permission: horse.horse
    usage: |-
      /h - Open horse menu
      /h claim - Claim your horse
      /h list - List your horses
      /h here - Bring the horse
      /h info - Information about your horse
      /h registerbrand - Register brand
      /h brandlist - List brands
      /h help - Usage
  horseadmin:
    aliases: [ha]
    description: Admin interface
    permission: horse.admin
    usage: |-
      /ha - Overview
      /ha new - Edit new horse
      /ha edit - Edit existing horse
      /ha deletebrand <owner> - Delete horse brand
permissions:
  horse.horse:
    description: Use /h
    default: op
  horse.admin:
    description: Use /ha
    default: op